app/routes.py
import os, re, uuid, subprocess, threading, logging, discord, asyncio, requests, boto3
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify, send_from_directory
from flask import abort, current_app, copy_current_request_context, Flask, Response, g, send_file
from flask_login import login_required, current_user, login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, login_manager
from .models import User, Upload
from .discord_bot import bot, send_embed
from datetime import datetime
from botocore.exceptions import NoCredentialsError

app= Flask(__name__)

BUCKET_NAME = 'mediasite-thumbnail-storage'

# Create a Blueprint for your routes
auth_bp = Blueprint('auth', __name__)

# Global dictionary to hold encoding progress for each job
encoding_lock = threading.Lock()
encoding_progress = {}

# Define allowed file extensions
ALLOWED_EXTENSIONS_IMAGES = {'png', 'jpg', 'jpeg', 'gif'}
ALLOWED_EXTENSIONS_VIDEOS = {'mp4', 'mov', 'avi'}

# Combine them into a single variable for the template
ALLOWED_EXTENSIONS = {
    'images': ALLOWED_EXTENSIONS_IMAGES,
    'videos': ALLOWED_EXTENSIONS_VIDEOS
}

def init_app(app):
    """Initialize routes with the given app instance."""
    app.register_blueprint(auth_bp)  # Register the blueprint for routes

# Function to check if a file has an allowed extension
def allowed_file(filename, allowed_extensions):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed_extensions

def encode_video_and_save(input_path, output_path, job_id, title, user_id):
    global encoding_progress

    with encoding_lock:
        encoding_progress[job_id] = 0  # Initialize progress to 0%

    command = [
        'ffmpeg', '-stats', '-i', input_path, '-c:v', 'h264_nvenc',
        '-preset', 'slow', '-profile:v', 'high', '-tune', 'hq',
        '-rc', 'vbr', '-b:v', '10M', '-maxrate', '10M', '-bufsize', '20M',
        '-c:a', 'aac', '-b:a', '192k', '-movflags', 'faststart', '-y', output_path
    ]

    try:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    except Exception as e:
        logging.error(f"Error starting encoding process: {e}")
        return  # Exit if subprocess fails to start

    regex = re.compile(r'time=(\d{2}):(\d{2}):(\d{2})\.(\d{2})')
    duration_regex = re.compile(r'Duration: (\d{2}):(\d{2}):(\d{2})\.(\d{2})')

    duration = None
    while True:
        output = process.stderr.readline()
        if output == '' and process.poll() is not None:
            break  # Exit loop if no more output and process has finished

        if output:
            logging.debug(f"FFmpeg output: {output.strip()}")

            # Try to extract duration early on
            if duration is None:
                duration_output = duration_regex.search(output)
                if duration_output:
                    hours = int(duration_output.group(1))
                    minutes = int(duration_output.group(2))
                    seconds = int(duration_output.group(3))
                    milliseconds = int(duration_output.group(4))
                    duration = hours * 3600 + minutes * 60 + seconds + milliseconds / 100
                    logging.debug(f"Extracted total duration: {duration} seconds")
            
            # Continue if we can calculate progress
            if duration:
                match = regex.search(output)
                if match:
                    # Extract current time from the output
                    hours = int(match.group(1))
                    minutes = int(match.group(2))
                    seconds = int(match.group(3))
                    milliseconds = int(match.group(4))
                    current_time = hours * 3600 + minutes * 60 + seconds + milliseconds / 100

                    logging.debug(f"Extracted current time: {current_time} seconds")

                    if duration > 0:
                        progress = (current_time / duration) * 100
                        progress = min(progress, 100)  # Cap the progress at 100%
                        logging.debug(f"Current time: {current_time}, Duration: {duration}, Progress calculated: {progress}%")
                        with encoding_lock:
                            encoding_progress[job_id] = int(progress)  # Update progress
                            logging.debug(f"Job ID: {job_id}, Progress updated: {encoding_progress[job_id]}%")
            else:
                logging.debug(f"Duration not available yet.")

    process.wait()  # Wait for the FFmpeg process to finish

    with encoding_lock:
        del encoding_progress[job_id]

    if process.returncode == 0:
        try:
            logging.debug(f"Current user ID: {user_id}")  # Corrected to use user_id parameter
            with current_app.app_context():
                delete_and_save(input_path, output_path, title, user_id)
        except Exception as e:
            logging.error(f"Error in delete_and_save: {e}")
    else:
        logging.error(f"Encoding failed for job ID: {job_id} with return code: {process.returncode}")

def delete_and_save(input_path, output_path, title, user_id):
    try:
        if os.path.exists(input_path):
            os.remove(input_path)
            logging.debug(f"Deleted original video: {input_path}")
        else:
            logging.debug(f"Original video not found for deletion: {input_path}")

        # Create a new upload instance, initially set thumbnail to placeholder
        new_upload = Upload(title=title, filename=os.path.basename(output_path), user_id=user_id, thumbnail='placeholder.jpg')
        db.session.add(new_upload)
        db.session.commit()  # Commit to save the new upload info

        logging.debug(f"Upload info saved for: {os.path.basename(output_path)} with ID: {new_upload.id}")

        # Generate the thumbnail and update the record
        thumbnail_filename = generate_thumbnail(output_path, new_upload.id)

        # Update thumbnail if generated successfully
        with current_app.app_context():
            upload = Upload.query.get(new_upload.id)
            if thumbnail_filename:
                upload.thumbnail = thumbnail_filename
            db.session.commit()

    except Exception as e:
        logging.error(f"Error deleting original video or saving upload info: {e}")

def generate_thumbnail(output_path, upload_id):
    thumbnail_filename = os.path.basename(output_path).replace('.mp4', '.jpg')
    thumbnail_path = os.path.join(current_app.config['UPLOAD_FOLDER_THUMBNAILS'], thumbnail_filename)
    timestamp = "00:00:01"

    command = [
        'ffmpeg', '-i', output_path, '-ss', timestamp, '-vframes', '1',
        '-vf', 'scale=480:-1', '-y', thumbnail_path
    ]

    try:
        subprocess.run(command, check=True)
        logging.debug(f"Thumbnail generated at: {thumbnail_path}")
        
        # After successful generation, upload the thumbnail to S3
        upload_success = upload_image_to_s3(thumbnail_path, BUCKET_NAME, f"thumbnails/{thumbnail_filename}")
        if upload_success:
            print("Thumbnail uploaded to S3 successfully.")
        
        return thumbnail_filename  # Return the thumbnail filename on success

    except subprocess.CalledProcessError as e:
        logging.error(f"Error generating thumbnail: {e}")
        return None  # Return None if thumbnail generation fails
    
def upload_image_to_s3(file_path, bucket_name, object_name=None):
    """
    Uploads a file to an S3 bucket with public read access.

    :param file_path: Path to the file to upload.
    :param bucket_name: S3 bucket name.
    :param object_name: S3 object name. Defaults to the file name if not specified.
    :return: True if file was uploaded successfully, else False.
    """
    if object_name is None:
        object_name = os.path.basename(file_path)
    
    s3_client = boto3.client('s3')
    
    try:
        s3_client.upload_file(
            file_path, bucket_name, object_name,
        )
        print(f"Uploaded {file_path} to {bucket_name}/{object_name} successfully.")
        return True
    except FileNotFoundError:
        print("File not found.")
        return False
    except NoCredentialsError:
        print("AWS credentials not available.")
        return False

def clean_filename(filename):
    # Remove leading and trailing spaces
    filename = filename.strip()
    # Replace spaces with underscores
    filename = filename.replace(' ', '_')
    # Remove or replace unwanted characters
    filename = re.sub(r'[^\w\-_\.]', '', filename)  # Only allow alphanumeric, underscores, dashes, and dots
    return filename

def get_upload_by_id(upload_id):
    return Upload.query.get(upload_id)

def exists(file_url):
    response = requests.head(file_url)
    return response.status_code == 200

def delete_upload_from_db(upload_id):
    upload = get_upload_by_id(upload_id)  # Assuming this function retrieves the upload
    if upload:
        try:
            db.session.delete(upload)  # Assuming you're using SQLAlchemy
            db.session.commit()
            return True
        except Exception as e:
            logging.error(f"Error deleting upload from database: {e}")
            db.session.rollback()  # In case of any issue
            return False
    return False

@app.before_request
def log_request_info():
    logging.basicConfig(level=logging.INFO)
    logging.info('Request Path: %s', request.path)

# User loader for Flask-Login (required)
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# Route: Home (protected, login required)
@auth_bp.route('/') 
def home():
    logging.debug("Index route hit")  # Debugging line
    return redirect(url_for('auth.gallery'))

# Route: Registration
@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']

app/templates/embed_video.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Open Graph Tags -->
    <meta property="og:site_name" content="Media Site" />
    <meta property="og:title" content="{{ upload.title }}" />
    <meta property="og:description" content="Check out this media!" />
    <meta property="og:type"
        content="{% if upload.filename.split('.')[-1] in allowed_extensions['videos'] %}video.other{% else %}website{% endif %}" />
    <meta property="og:url" content="{{ request.url }}" />

    <!-- Conditional tags based on media type -->
    {% if upload.filename.split('.')[-1] in allowed_extensions['videos'] %}
    <!-- Video specific tags -->
    <meta property="og:video"
        content="{{ url_for('embed_video', filename=upload.filename, _external=True, _scheme='https') }}" />
    <meta property="og:video:secure_url"
        content="{{ url_for('embed_video', filename=upload.filename, _external=True, _scheme='https') }}" />
    <meta property="og:video:type" content="video/mp4" />
    <meta property="og:video:width" content="1280" />
    <meta property="og:video:height" content="720" /> <!-- Add height if needed -->
    {% else %}

    <!-- Image specific tags -->
    <meta property="og:image"
        content="{{ url_for('static', filename='images/' + upload.filename, _external=True, _scheme='https') }}" />
    <meta property="og:image:secure_url"
        content="{{ url_for('static', filename='images/' + upload.filename, _external=True, _scheme='https') }}" />
    <meta property="og:image:type" content="image/png" />

    {% endif %}
    <title>Embedded Video</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #000;
        }

        video {
            max-width: 100%;
            max-height: 100%;
        }
    </style>
</head>

<body>
    <video controls>
        <source src="{{ url_for('serve_video', filename=filename, _external=True, _scheme='https') }}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
</body>

</html>

app/templates/gallery.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <link href="https://vjs.zencdn.net/7.20.3/video-js.css" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/gallery_styles.css') }}"
    />
    <script src="https://vjs.zencdn.net/7.20.3/video.min.js"></script>
    <title>Your Gallery</title>
  </head>

  <body>
    <h1>Your Gallery</h1>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class="flash-message" style="color: red; text-align: center; transition: opacity 0.5s ease-in-out;">
          {{ messages[0][1] }}
        </div>
        <script>
          // Hide the flash message after 2 seconds
          setTimeout(function () {
            const flashMessage = document.querySelector('.flash-message');
            if (flashMessage) {
              flashMessage.style.opacity = '0';  // Fades the message out
            }
          }, 1000);

          // Optionally, remove the message element entirely after fade-out (e.g., after 2.5 seconds)
          setTimeout(function () {
            const flashMessage = document.querySelector('.flash-message');
            if (flashMessage) {
              flashMessage.remove();
            }
          }, 2500);
        </script>
      {% endif %}
    {% endwith %}

    <nav>
      <a href="{{ url_for('auth.logout') }}">Logout</a>
      <a href="{{ url_for('auth.upload_file') }}">Upload</a>
    </nav>

    <div class="gallery">
      <div class="upload-container">
        {% for upload in uploads %}
        <div class="upload" id="media-{{ upload.id }}">
          <h2>
            {{ upload.title }} {% if upload.filename.endswith(('png', 'jpg',
            'jpeg', 'gif')) %}
            <i class="fas fa-image" title="Image"></i>
            {% elif upload.filename.endswith(('mp4', 'mov', 'avi')) %}
            <i class="fas fa-video" title="Video"></i>
            {% endif %}
          </h2>

          {% if upload.filename.endswith(('png', 'jpg', 'jpeg', 'gif')) %}
          <img
            src="{{ url_for('static', filename='images/' + upload.filename) }}"
            alt="{{ upload.title }}"
            onclick="openModal('{{ url_for('static', filename='images/' + upload.filename) }}', 'image', {{ upload.id }}, '{{ upload.share_token }}')"
          />
          {% elif upload.filename.endswith(('mp4', 'mov', 'avi')) %}
          <video
            data-src="{{ url_for('static', filename='videos/' + upload.filename) }}"
            onclick="openModal('{{ url_for('static', filename='videos/' + upload.filename) }}', 'video', {{ upload.id }}, '{{ upload.share_token }}'); event.stopPropagation();"
            width="200"
            controlslist="nodownload nofullscreen noremoteplayback"
            disablepictureinpicture
          >
            <source
              src="{{ url_for('static', filename='videos/' + upload.filename) }}"
              type="video/mp4"
            />
            <p>
              Your browser does not support the video tag. Video URL: {{
              url_for('static', filename='videos/' + upload.filename) }}
            </p>
          </video>
          {% endif %}

          <button onclick="deleteMedia({{ upload.id }})">Delete</button>
        </div>
        {% else %}
        <p>You have no uploads yet.</p>
        {% endfor %}
      </div>
    </div>

    <!-- Modal Structure -->
    <div id="mediaModal" class="modal">
      <span class="close" onclick="closeModal()">&times;</span>
      <img id="modalImage" class="modal-content" style="display: none" />

      <div class="video-container" style="display: none">
        <video
          id="modalVideo"
          class="video-js vjs-default-skin"
          controls
          preload="auto"
          width="640"
          height="264"
          controlslist="nodownload nofullscreen noremoteplayback"
          disablepictureinpicture
        >
          <source id="videoSource" src="" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>

      <!-- Share button container -->
      <div class="share-container" style="text-align: center; margin-top: 10px">
        <button id="shareButton">Share</button>
        <button
          id="shareDiscordButton"
          style="display: none"
          onclick="openDiscordShareModal()"
        >
          Share in Discord
        </button>
        <!-- Initial display set to none -->
      </div>

      <!-- Discord Share Modal -->
      <div id="discordShareModal" class="modal-content" style="display: none">
        <h2>Share in Discord</h2>
        <label for="uploaderName">Uploader Name:</label>
        <input
          type="text"
          id="uploaderName"
          placeholder="Enter Uploader Name"
          autocomplete="off"
          required
        />

        <label for="discordChannelID">Discord Channel ID:</label>
        <input
          type="text"
          id="discordChannelID"
          placeholder="Enter Discord Channel ID"
          required
        />

        <input type="hidden" id="uploadId" />
        <!-- Hidden input for upload ID -->

        <button onclick="submitDiscordShare()">Share in Discord</button>
        <button onclick="closeDiscordShareModal()">Cancel</button>
      </div>
    </div>

    <script src="{{ url_for('static', filename='scripts/gallery_scripts.js') }}"></script>
  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/login_styles.css') }}"
    />
  </head>

  <body>
    <h1>Login</h1>

    <!-- Flash messages display -->
    {% with messages = get_flashed_messages(with_categories=True) %} {% if
    messages %}
    <ul class="flashes">
      {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %}

    <form method="POST" action="{{ url_for('auth.login') }}">
      <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" name="username" required />
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" name="password" required />
      </div>
      <input type="submit" value="Login" class="submit-button" />
    </form>

    <p>
      Don't have an account?
      <a class="button" href="{{ url_for('auth.register') }}">Register</a>
    </p>
  </body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/register_styles.css') }}"> <!-- Link to the CSS file -->
</head>

<body>
    <h1>Register</h1>
    <form action="{{ url_for('auth.register') }}" method="POST"> <!-- Updated action URL -->
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required><br><br>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br><br>

        <button type="submit">Register</button>
    </form>
    <p>Already have an account? <a href="{{ url_for('auth.login') }}">Login here</a></p> <!-- Updated link -->
</body>

</html>

app/templates/upload.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Media</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/upload_styles.css') }}">
</head>

<body>
    <div class="container">
        <h1>Upload Media</h1>
        <form id="uploadForm" action="{{ url_for('auth.upload_file') }}" method="POST" enctype="multipart/form-data">
            <label for="title">Title:</label>
            <input type="text" name="title" autocomplete="off" required>
            <br><br>
            <label for="file">Select file:</label>
            <input type="file" name="file" accept="image/*,video/*" required>
            <br><br>
            <input type="submit" value="Upload">
            <br>
            <div id="uploadProgressContainer" class="progress-container" style="display: none;">
                <div id="uploadProgress" class="progress-bar" style="width: 0%;">0%</div>
            </div>
            <div id="encodingProgressContainer" class="progress-container" style="display: none;">
                <div id="encodingProgress" class="progress-bar" style="width: 0%;">0%</div>
            </div>
        </form>
        <br>
        <a href="{{ url_for('auth.logout') }}">Logout</a>
    </div>
    <script src="{{ url_for('static', filename='scripts/upload_scripts.js') }}"></script>
</body>

</html>

app/templates/view_shared_media.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- HTML Meta Tags -->
    <title>{{ upload.title }}</title>
    <meta name="description" content="Check out this media uploaded by {{ username }}!" />

    <!-- Conditional Meta Tags for Thumbnail -->
    {% if upload.filename.split('.')[-1] in allowed_extensions['videos'] %}
      <meta property="og:image" content="https://mediasite-thumbnail-storage.s3.us-east-1.amazonaws.com/thumbnails/{{ thumbnail }}">
      <meta name="twitter:image" content="https://mediasite-thumbnail-storage.s3.us-east-1.amazonaws.com/thumbnails/{{ thumbnail }}">
      <meta property="twitter:player" content="{{ url_for('auth.stream_video', filename=upload.filename, _external=True, _scheme='https') }}">
      <meta property="twitter:player:stream:content_type" content="video/mp4" />
      {% elif upload.filename.split('.')[-1] in allowed_extensions['images'] %}
      <meta property="og:image" content="{{ url_for('static', filename='images/' + upload.filename, _external=True, _scheme='https') }}">
      <meta name="twitter:image" content="{{ url_for('static', filename='images/' + upload.filename, _external=True, _scheme='https') }}">
    {% endif %}

    <meta property="twitter:domain" content="breadgameserver.duckdns.org" />
    <!-- <meta name="twitter:title" content="{{ upload.title }}" /> -->
    <meta property="og:description" content="Check out this media uploaded by {{ username }}!" />
    <meta property="og:site_name" content="Bread's Video Host" />
    <meta name="twitter:description" content="Check out this media uploaded by {{ username }}!" />
    <meta name="twitter:card" content="{% if upload.filename.split('.')[-1] in allowed_extensions['videos'] %}player{% else %}summary_large_image{% endif %}" />
    <meta property="og:video:type" content="text/html">
    <meta property="og:video:width" content="492">
    <meta property="og:video:height" content="270">
    <meta name="theme-color" content="#dad4bb">
    <!-- <meta http-equiv="refresh" content="0;url= {{ url_for('auth.serve_video', filename=upload.filename, _external=True, _scheme='https') }}"> -->

    <link href="https://vjs.zencdn.net/7.20.3/video-js.css" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/view_shared_media_styles.css') }}"
    />
    <title>{{ username }}'s Media</title>
  </head>

  <body>
    <header>
      <h1>{{ upload.title }}</h1>
      <a href="{{ url_for('auth.home') }}" class="home-button">Home</a>
    </header>

    <main class="media-container">
      {% if upload.filename.split('.')[-1] in allowed_extensions['videos'] %}
      <div class="video-container">
        <video
          id="modalVideo"
          class="video-js vjs-default-skin"
          controls
          preload="auto"
          width="1280"
          height="720"
          controlslist="nodownload nofullscreen noremoteplayback"
          disablepictureinpicture
        >
          <source
            id="videoSource"
            src="{{ url_for('auth.stream_video', filename= upload.filename, _external=True, _scheme='https') }}"
            type="video/mp4"
          />
          Your browser does not support the video tag.
        </video>
      </div>
      {% elif upload.filename.split('.')[-1] in allowed_extensions['images'] %}
      <img
        src="{{ url_for('static', filename='images/' + upload.filename, _external=True, _scheme='https') }}"
        alt="{{ upload.title }}"
        class="media-image"
      />
      {% else %}
      <p>Unsupported media type.</p>
      {% endif %}
    </main>

    <script src="https://vjs.zencdn.net/7.20.3/video.min.js"></script>
    <script>
      var player = videojs("modalVideo", {
        controls: true,
        autoplay: false,
        preload: "auto",
      });
    </script>
  </body>
</html>